### ISSUE TITLE
Log origin address rather than proxy

### ISSUE THREAD

**Issue by retzkek** [opensciencegrid/gracc-collector#17]
Currently logs include the request's `RemoteAddr`, but since requests are going through a reverse proxy this is not terribly useful. Should look for and use `X-Real-IP` or `X-Forwarded-For` headers if present (and need to make sure these are being set in the proxy).

**Comment by djw8605** [comment]
@retzkek could I take this one?  I would like to practice my Go.

**Comment by retzkek** [comment]
Definitely! Let me know if you need any help. Here's the line in particular: https://github.com/opensciencegrid/gracc-collector/blob/master/collector.go#L167
