### ISSUE TITLE
Handle StorageElement and StorageElementRecord records

### ISSUE THREAD

**Issue by retzkek** [opensciencegrid/gracc-collector#5]
These need to be flattened to JSON similarly to JobUsageRecord. A `type` field will be used to indicate the type of record. They will all go through the same processing stream.

**Comment by djw8605** [comment]
The summarizer currently doesn't limit it's summarizing to just the JobUsageRecord type (maybe it should) when it queries the raw index.  Should that change be made first?

**Comment by retzkek** [comment]
@djw8605 yes, and ideally I think the summarization or replay request should specify the type, rather than it being hardcoded. These different types may end up in different pipelines to different indices, but the flexibility should be there.

There's higher priority changes for the request and summary agents right now though.

**Comment by retzkek** [comment]
Fixed by #8
